Repository Bul-4-Jo/Recipick, pull requests merged in 2022-12, with the labels that each got.

#5 [Feat] 프로필 썸네일 컴포넌트 구현 #4
  src/Assets/Images/img_profile_basic.png
  src/Components/Common/ProfileThumb/ProfileThumb.jsx
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
Labels: ✨ Feature, 🎨 Html&css

#7 [Feat] 하단 탭 메뉴 컴포넌트 구현
  src/Assets/Icons/icon_chat.png
  src/Assets/Icons/icon_chat_fill.png
  src/Assets/Icons/icon_home.png
  src/Assets/Icons/icon_home_fill.png
  src/Assets/Icons/icon_post.png
  src/Assets/Icons/icon_profile.png
  src/Assets/Icons/icon_profile_fill.png
  src/Components/Common/TabMenu/TabMenu.jsx
  src/Components/Common/TabMenu/TabMenu.style.jsx
Labels: ✨ Feature, 🎨 Html&css

#10 [Styled] alert 컴포넌트 구현
  src/Components/Common/Alert/Alert.jsx
  src/Components/Common/Alert/Alert.style.jsx
Labels: 🎨 HTML&CSS

#12 Design: 프로필 썸네일 컴포넌트 medium 사이즈 추가 #11
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
Labels: 🎨 HTML&CSS

#15 Design: button 컴포넌트 스타일 구현 및 오타 수정
  src/Components/Common/Button/Button.jsx
  src/Components/Common/Button/Button.style.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#20 [Styled] 프로필 썸네일 컴포넌트 large 사이즈 추가
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
Labels: 🎨 HTML&CSS

#23 Feat: 유저 검색 페이지 마크업, 스타일링 구현 및 svg 파일 추가
  src/Assets/Icons/icon_arrow_left.png
  src/Assets/Icons/icon_image.png
  src/Assets/Icons/icon_more_vertical.png
  src/Assets/Icons/icon_search.png
  src/Assets/Icons/icon_search1.png
  src/Assets/Icons/s_icon_more_vertical.png
  src/Assets/Icons/svg/Google__G__Logo 1.svg
  src/Assets/Icons/svg/facebook.svg
  src/Assets/Icons/svg/iccon_img_layers.svg
  src/Assets/Icons/svg/icon_ more_vertical.svg
  src/Assets/Icons/svg/icon_arrow_left.svg
  src/Assets/Icons/svg/icon_chat.svg
  src/Assets/Icons/svg/icon_chat_fill.svg
  src/Assets/Icons/svg/icon_heart.svg
  src/Assets/Icons/svg/icon_home.svg
  src/Assets/Icons/svg/icon_home_fill.svg
  src/Assets/Icons/svg/icon_image.svg
  src/Assets/Icons/svg/icon_message_circle_1.svg
  src/Assets/Icons/svg/icon_more_vertical.svg
  src/Assets/Icons/svg/icon_post.svg
  src/Assets/Icons/svg/icon_post_album_off.svg
  src/Assets/Icons/svg/icon_post_album_on.svg
  src/Assets/Icons/svg/icon_post_list_off.svg
  src/Assets/Icons/svg/icon_post_list_on.svg
  src/Assets/Icons/svg/icon_profile.svg
  src/Assets/Icons/svg/icon_profile_fill.svg
  src/Assets/Icons/svg/icon_search.svg
  src/Assets/Icons/svg/icon_share.svg
  src/Assets/Icons/svg/kokoa_sns.svg
  src/Assets/Icons/svg/s_icon_more_vertical.svg
  src/Assets/Icons/svg/x.svg
  src/Components/UserSearch.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Main/Search/Search.style.jsx
Labels: 🎨 HTML&CSS

#26 [Styled] 상품 업로드 페이지 마크업 및 스타일링
  src/Assets/Images/btn_upload_file_gray.png
  src/Components/ProductEdit/ProductImg/ProductImg.jsx
  src/Components/ProductEdit/ProductImg/ProductImg.style.jsx
  src/Components/ProductEdit/ProductInput/ProductInput.jsx
  src/Components/ProductEdit/ProductInput/ProductInput.style.jsx
  src/Pages/Product/ProductEdit/ProductEdit.jsx
  src/Pages/Product/ProductEdit/ProductEdit.style.jsx
Labels: 🎨 HTML&CSS

#32 [Styled] 상품 업로드 페이지 마크업 및 스타일링
  src/Components/Product/Product.jsx
  src/Components/Product/Product.style.jsx
  src/Components/Product/ProductItem/ProductItem.jsx
  src/Components/Product/ProductItem/ProductItem.style.jsx
Labels: 🎨 HTML&CSS

#37 [Styled] 게시글 업로드 페이지 마크업 및 스타일링
  src/Assets/Icons/icon_x.png
  src/Assets/Images/btn_upload_file.png
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.style.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/PostEdit/PostForm/PostForm.style.jsx
  src/Components/PostEdit/PostImg/PostImg.jsx
  src/Components/PostEdit/PostImg/PostImg.style.jsx
  src/Pages/Post/PostEdit/PostEdit.jsx
  src/Pages/Post/PostEdit/PostEdit.style.jsx
Labels: 🎨 HTML&CSS

#24 [Feat] modal 컴포넌트 구현
  src/Components/Common/Modal/Modal.jsx
  src/Components/Common/Modal/Modal.style.jsx
  src/Style/GlobalTheme.js
Labels: ✨ Feature, 🎨 HTML&CSS

#34 [Styled] 팔로워 리스트 페이지 마크업 및 스타일링
  src/Components/FollowersItem/FollowersItem.jsx
  src/Components/FollowersItem/FollowersItem.style.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
  src/Pages/Main/Profile/Followers/Followers.style.jsx
Labels: 🎨 HTML&CSS

#33 [Design] LoginForm 컴포넌트 구현
  src/Assets/Images/logo_white.svg
  src/Components/LoginForm/LoginForm.jsx
  src/Components/LoginForm/LoginForm.style.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Login/Login.style.jsx
  src/Routes/Router.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#31 [Fix] 버튼 active시 background-color, outline 적절히 동작하도록 변경
  src/Components/Common/Button/Button.style.jsx
Labels: 🐞 BugFix

#44 [Fix] 이미지 업로드 버튼 컬러 변경
  src/Assets/Images/btn_upload_file.png
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.jsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#42 [Styled] 회원가입 시 프로필 설정 페이지 마크업 및 스타일링
  src/Assets/Images/btn_upload_file_mainColor.png
  src/Pages/Signup/Profile/ProfileEdit.jsx
  src/Pages/Signup/Profile/ProfileEdit.style.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#36 [Styled] 유저 검색 리스트 마크업 및 스타일링
  src/Components/Common/Header/SearchHeader.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Main/Search/Search.style.jsx
  src/Pages/Main/Search/SearchBar.jsx
  src/Pages/Main/Search/SearchBar.style.jsx
  src/Pages/Main/Search/SearchUserItem.jsx
  src/Pages/Main/Search/SearchUserItem.style.jsx
Labels: 🎨 HTML&CSS

#50 [Fix] 제품 이미지 배경 색 수정 및 placeholder 추가
  src/Components/ProductEdit/ProductImg/ProductImg.style.jsx
  src/Components/ProductEdit/ProductInput/ProductInput.jsx
  src/Components/ProductEdit/ProductInput/ProductInput.style.jsx
  src/Style/GlobalTheme.js
Labels: 🐞 BugFix, 🎨 HTML&CSS

#46 [Feat] 팔로워 리스트 요청 및 팔로우, 언팔로우 기능 구현
  src/Components/FollowersItem/FollowersItem.jsx
  src/Components/FollowersItem/FollowersItem.style.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
Labels: 📡 API, ✨ Feature

#40 [Style] 회원가입 페이지 마크업 및 스타일링
  src/Pages/Signup/Signup.jsx
  src/Pages/Signup/Signup.style.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#60 [Fix] 헤더 마크업 및 스타일링 수정
  src/Assets/Icons/icon_search.png
  src/Components/Common/Header/BasicHeader.jsx
  src/Components/Common/Header/ChatHeader.jsx
  src/Components/Common/Header/MainHeader.jsx
  src/Components/Common/Header/SearchHeader.jsx
  src/Components/Common/Header/UploadHeader.jsx
  src/Pages/NotFound/NotFound.jsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#63 [Refactor] 컴포넌트 수정 및 리펙토링
  src/Components/Common/Alert/Alert.jsx
  src/Components/Common/Alert/Alert.style.jsx
  src/Components/Common/Button/Button.jsx
  src/Components/Common/Button/Button.style.jsx
  src/Components/Common/Header/BasicHeader.jsx
  src/Components/Common/Header/ChatHeader.jsx
  src/Components/Common/Header/MainHeader.jsx
  src/Components/Common/Header/SearchHeader.jsx
  src/Components/Common/Header/UploadHeader.jsx
  src/Components/Common/Layout/Layout.jsx
  src/Components/Common/Layout/Layout.style.jsx
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
  src/Components/Common/TabMenu/TabMenu.jsx
  src/Components/Common/TabMenu/TabMenu.style.jsx
  src/Components/Common/UserInfo/UserInfo.jsx
  src/Components/Common/UserInfo/UserInfo.style.jsx
  src/Components/FollowersItem/FollowersItem.jsx
  src/Components/LoginForm/LoginForm.jsx
  src/Components/Product/Product.style.jsx
  src/Pages/Main/Search/SearchBar.style.jsx
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Profile/ProfileSet.style.jsx
  src/Pages/Signup/Signup.jsx
  src/Routes/Router.jsx
  src/Style/GlobalStyle.jsx
  src/Style/GlobalTheme.js
Labels: 🔨 Refactor

#56 [Feat] 홈 피드 페이지 마크업 & 팔로워 게시글 목록 데이터 요청
  src/Assets/Images/logo_character.svg
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/HomeFeed/HomeFeed.style.jsx
Labels: 📡 API, ✨ Feature, 🎨 HTML&CSS

#57 [Styled] NotFound 페이지 컴포넌트 마크업 및 스타일링
  src/Assets/Images/NotFound_img.svg
  src/Pages/NotFound/NotFound.jsx
  src/Pages/NotFound/NotFound.style.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#61 Design: 게시물 상세페이지: 댓글 섹션, 댓글리스트, 댓글 입력창 마크업 및 스타일 구현
  src/Components/comment/MyCommentInput.jsx
  src/Components/comment/UserComment.jsx
  src/Components/comment/UserInfo.jsx
  src/Components/comment/comment.style.jsx
  src/Components/comment/commentItem.style.jsx
  src/Pages/Comment/Comment.jsx
  src/Routes/Router.jsx
Labels: 🎨 HTML&CSS

#59 [Feat] 게시물 컨텐츠 마크업 및 스타일링
  src/Components/PostContent/PostContent.jsx
  src/Components/PostContent/PostContent.style.jsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#58 [Feat] 프로필 페이지 마크업 및 스타일링
  src/Assets/Icons/icon_back.png
  src/Assets/Icons/icon_more.png
  src/Assets/Icons/icon_share.png
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#65 [Refactor] 컴포넌트 수정 및 레이아웃 설정
  src/Assets/Images/logo.svg
  src/Components/Common/BtnUpload/BtnUpload.jsx
  src/Components/Common/BtnUpload/BtnUpload.style.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Header/Header.style.jsx
  src/Components/Common/Layout/Layout.jsx
  src/Components/Common/Layout/Layout.style.jsx
  src/Components/LoginForm/LoginForm.style.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.style.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/PostEdit/PostImg/PostImg.style.jsx
  src/Components/Product/Product.jsx
  src/Components/Product/Product.style.jsx
  src/Components/ProductEdit/ProductImg/ProductImg.style.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Login/Login.style.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Main/Search/Search.style.jsx
  src/Pages/Main/Search/SearchUserItem.style.jsx
  src/Pages/Post/PostEdit/PostEdit.jsx
  src/Pages/Post/PostEdit/PostEdit.style.jsx
  src/Pages/Product/ProductEdit/ProductEdit.style.jsx
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Profile/ProfileSet.style.jsx
  src/Pages/Splash.jsx
  src/Routes/Router.jsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor

#66 [Fix]: CommentInput font-family 적용 및 기타 수정
  src/Components/comment/MyCommentInput.jsx
  src/Components/comment/UserComment.jsx
  src/Components/comment/comment.style.jsx
  src/Components/comment/commentItem.style.jsx
  src/Pages/Comment/Comment.jsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#67 Refactor: 컴포넌트 리팩토링
  src/Components/Common/BtnUpload/BtnUpload.style.jsx
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/GetPost/GetPost.style.jsx
  src/Components/Common/Header/BasicHeader.jsx
  src/Components/Common/Header/ChatHeader.jsx
  src/Components/Common/Header/MainHeader.jsx
  src/Components/Common/Header/SearchHeader.jsx
  src/Components/Common/Header/UploadHeader.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
  src/Components/FollowersItem/FollowersItem.jsx
  src/Components/PostContent/PostContent.jsx
  src/Components/PostContent/PostContent.style.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.jsx
  src/Components/Product/Product.style.jsx
  src/Components/ProfileEdit/ProfileEdit.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.style.jsx
  src/Components/comment/MyCommentInput.jsx
  src/Components/comment/MyCommentInput.style.jsx
  src/Components/comment/UserComment.jsx
  src/Components/comment/UserInfo.jsx
  src/Components/comment/comment.style.jsx
  src/Components/comment/commentItem.style.jsx
  src/Pages/Comment/Comment.jsx
  src/Pages/Comment/Comment.style.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
  src/Pages/NotFound/NotFound.jsx
  src/Pages/NotFound/NotFound.style.jsx
  src/Pages/Post/PostEdit/PostEdit.jsx
  src/Routes/Router.jsx
Labels: 🔨 Refactor

#71 [Refactor] UserInfo 컴포넌트 내 불필요한 요소 및 스타일 삭제
  src/Components/Common/UserInfo/UserInfo.jsx
  src/Components/Common/UserInfo/UserInfo.style.jsx
  src/Components/FollowersItem/FollowersItem.jsx
  src/Components/FollowersItem/FollowersItem.style.jsx
  src/Components/comment/commentItem.style.jsx
  src/Pages/Main/Profile/Followers/Followers.style.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Main/Search/SearchUserItem.style.jsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#75 [Feat] 내 프로필 페이지 : 헤더 모달창 띄우는 기능
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Layout/Layout.jsx
  src/Components/Common/Modal/Modal.jsx
  src/Components/Common/Modal/Modal.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: ✨ Feature

#78 [Feat] 팔로잉 페이지 구현
  src/API/api.js
  src/Pages/Main/Profile/Following/Following.jsx
  src/Pages/Main/Profile/Following/Following.style.jsx
Labels: 📡 API, ✨ Feature, 🎨 HTML&CSS

#79 [Styled] 프로필 설정 페이지 스타일링 수정
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Profile/ProfileSet.style.jsx
Labels: 🎨 HTML&CSS

#73 [Feat] Followers 페이지 Axios API 호출 코드 분리
  src/Components/FollowItem/FollowItem.jsx
  src/Components/FollowItem/FollowItem.style.jsx
  src/Components/FollowersItem/FollowersItem.jsx
  src/Components/FollowersItem/FollowersItem.style.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
Labels: 📡 API, ✨ Feature

#83 [Feat] 로그인 기능 구현
  src/Components/LoginForm/LoginForm.jsx
  src/Components/LoginForm/LoginForm.style.jsx
  src/Pages/Login/Login.jsx
Labels: 📡 API, ✨ Feature

#81 [Feat] 회원 가입 기능 구현
  src/Components/Common/BtnUpload/BtnUpload.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.jsx
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Profile/ProfileSet.style.jsx
  src/Pages/Signup/Signup.jsx
  src/Pages/Signup/Signup.style.jsx
Labels: 📡 API, ✨ Feature, 🎨 HTML&CSS

#84 [Feat] 게시글 업로드 페이지 기능 구현
  src/API/api.js
  src/Assets/Icons/icon_x_dark.png
  src/Components/Common/BtnUpload/BtnUpload.jsx
  src/Components/Common/BtnUpload/BtnUpload.style.jsx
  src/Components/Common/Button/Button.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.jsx
  src/Components/PostEdit/BtnImgUpload/BtnImgUpload.style.jsx
  src/Components/PostEdit/PostBtn/PostBtn.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/PostEdit/PostForm/PostForm.style.jsx
  src/Components/PostEdit/PostImg/PostImg.jsx
  src/Components/PostEdit/PostImg/PostImg.style.jsx
  src/Components/PostEdit/PostTag/PostTag.jsx
  src/Components/PostEdit/PostTag/PostTag.style.jsx
  src/Components/PostEdit/PostText/PostText.jsx
  src/Components/PostEdit/PostText/PostText.style.jsx
  src/Hooks/useUploadFile.js
  src/Pages/Post/PostEdit/PostEdit.jsx
  src/Pages/Post/PostUpload/PostUpload.jsx
  src/Pages/Post/PostUpload/PostUpload.style.jsx
  src/Routes/Router.jsx
Labels: 📡 API, ✨ Feature

#86 [Feat] 게시물 좋아요 기능 구현
  src/Assets/Icons/svg/icon_heart_filled.svg
  src/Components/Reactions/CommentCounter.jsx
  src/Components/Reactions/LikeButton.jsx
  src/Components/Reactions/ReactionSection.jsx
  src/Components/Reactions/ReactionSection.style.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#88 [Feat] splash 화면 구현
  src/Pages/Splash.jsx
  src/Pages/Splash/Splash.jsx
  src/Pages/Splash/Splash.style.jsx
  src/Routes/Router.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#92 [Fix] 미 동작 버튼 , 프로필 설정 이미지 업로드 방법 수정
  src/Components/Common/BtnUpload/BtnUpload.jsx
  src/Components/Common/Button/Button.jsx
  src/Components/LoginForm/LoginForm.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.jsx
  src/Hooks/useUploadFile.js
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Signup.jsx
Labels: 📡 API, 🐞 BugFix

#93 [Feat] 프로필 페이지 기능 구현
  .gitignore
  src/API/api.js
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
  src/Components/Common/UserInfo/UserInfo.jsx
  src/Components/Common/UserInfo/UserInfo.style.jsx
  src/Components/Reactions/CommentCounter.jsx
  src/Components/Reactions/LikeButton.jsx
  src/Components/Reactions/ReactionSection.style.jsx
  src/Pages/Main/Chat/ChatList/ChatList.jsx
  src/Pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
Labels: 📡 API, ✨ Feature

#94 [Feat] 게시물 수정 페이지 구현
  src/API/api.js
  src/Components/PostEdit/PostBtn/PostBtn.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/PostEdit/PostText/PostText.jsx
  src/Hooks/useUploadFile.js
  src/Pages/Post/PostEdit/PostEdit.jsx
Labels: 📡 API, ✨ Feature

#96 [Feat] 판매 중인 상품 불러오기 및 프로필 페이지에 적용
  src/API/api.js
  src/Components/Product/Product.jsx
  src/Components/Product/ProductItem/ProductItem.jsx
  src/Components/Product/ProductItem/ProductItem.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: 📡 API, ✨ Feature

#100 [Feat] 상품 수정 페이지 구현
  src/API/api.js
  src/Components/ProductEdit/ProductBtn/ProductBtn.jsx
  src/Components/ProductEdit/ProductForm/ProductForm.jsx
  src/Pages/Product/ProductEdit/ProductEdit.jsx
Labels: 📡 API, ✨ Feature

#101 [Fix] 맥북에서 재료가 두 번 입력되는 이슈 수정
  src/Components/PostEdit/PostTag/PostTag.jsx
Labels: 🐞 BugFix

#103 [Feat] modal 기능 portal을 이용해서 구현
  public/index.html
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Layout/Layout.jsx
  src/Components/Common/Modal/Modal.jsx
  src/Components/Common/Modal/Modal.style.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Pages/Main/Chat/ChatList/ChatList.jsx
  src/Pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: 🐞 BugFix, ✨ Feature

#108 [Fix] 게시물 이미지 프리뷰 src 포맷 변경
  src/Components/PostEdit/PostImg/PostImg.jsx
Labels: 🐞 BugFix

#110 [Fix] 탭메뉴에서 로그인 한 유저의 프로필로 연결
  src/Components/Common/TabMenu/TabMenu.jsx
  src/Components/Common/TabMenu/TabMenu.style.jsx
Labels: 🐞 BugFix

#115 [Fix] alert창 portal을 이용해서 구현
  src/Components/Common/Alert/Alert.jsx
  src/Components/Common/Alert/Alert.style.jsx
  src/Components/Common/Header/Header.jsx
Labels: 🐞 BugFix, ✨ Feature

#111 [Feat] 홈 피드에 팔로잉 게시글 목록 불러오기
  src/API/api.js
  src/Components/Common/PostCard/PostCard.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/HomeFeed/HomeFeed.style.jsx
Labels: 📡 API, ✨ Feature

#116 [Design] 스크롤바 커스텀 스타일링 #113
  src/Style/GlobalStyle.jsx
Labels: 🎨 HTML&CSS

#118 [Feat] 토큰 검증을 통한 페이지 이동 구현
  src/Components/Common/Header/Header.jsx
  src/Components/Common/TabMenu/TabMenu.jsx
  src/Components/LoginForm/LoginForm.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Signup/Signup.jsx
  src/Pages/Splash/Splash.jsx
  src/Routes/AuthRoute.jsx
  src/Routes/NonAuthRoute.jsx
  src/Routes/Router.jsx
Labels: ✨ Feature

#120 [Fix] 프로필 페이지 내 해당 유저가 판매 중인 상품만 보이도록 수정
  src/Components/Product/Product.jsx
Labels: 🐞 BugFix

#121 Fix: userInfo 프로필 온전히 보이기, 홈피드 날짜 보이기
  src/Components/Common/PostAlbum/PostAlbum.style.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
Labels: 🔨 Refactor

#122 [Fix] 프로필 페이지 내 해당 유저가 판매 중인 상품만 보이도록 수정2 (state 이름 반영)
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: 🐞 BugFix

#126 [Feat] 판매 중인 상품 모달 기능 구현
  src/API/api.js
  src/Components/Common/Alert/Alert.jsx
  src/Components/Common/Modal/Modal.jsx
  src/Components/Product/Product.jsx
  src/Components/Product/ProductItem/ProductItem.jsx
  src/Pages/Product/ProductEdit/ProductEdit.jsx
Labels: 📡 API, 🐞 BugFix, ✨ Feature

#124 [Feat] 프로필 페이지 팔로우 버튼 기능 추가
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: 📡 API, ✨ Feature

#130 [Fix] 홈피드 이미지 안 나오는 이슈
  src/Pages/Main/HomeFeed/HomeFeed.jsx
Labels: 🐞 BugFix, ✨ Feature

#127 [Feat] 앨범형 게시물 불러오기 기능 구현
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/PostAlbum/PostAlbum.jsx
  src/Components/Common/PostAlbum/PostAlbum.style.jsx
  src/Components/Common/PostCard/PostCard.jsx
Labels: ✨ Feature

#129 [Feat] 상대 / 자신 프로필 구분해서 보여주는 기능 구현
  src/Components/Common/PostCard/PostCard.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Routes/Router.jsx
Labels: ✨ Feature

#133 [Feat] window 리사이즈 시 textarea 크기 조절
  src/Components/PostEdit/PostText/PostText.jsx
Labels: ✨ Feature

#136 [Feat] 유저 프로필 수정 페이지 기능 구현
  src/API/api.js
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Header/Header.style.jsx
  src/Components/Common/PostAlbum/PostAlbum.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.style.jsx
Labels: ✨ Feature

#135 [Feat] 채팅 리스트 페이지 구현
  src/Pages/Main/Chat/ChatList/ChatItem/ChatItem.jsx
  src/Pages/Main/Chat/ChatList/ChatItem/ChatItem.style.jsx
  src/Pages/Main/Chat/ChatList/ChatList.jsx
  src/Pages/Main/Chat/ChatList/ChatList.style.jsx
Labels: 📡 API, ✨ Feature, 🎨 HTML&CSS

#139 [Refactor] token 및 accountname을 로컬 스토리지에서 받아오도록 수정
  .gitignore
  src/API/api.js
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
Labels: 📡 API, 🔨 Refactor

#140 [Fix] 홈피드에서 이미지가 없는 게시물이 존재할 시 에러 발생하는 이슈
  src/Pages/Main/HomeFeed/HomeFeed.jsx
Labels: 🐞 BugFix, ✨ Feature
