Repository Bul-4-Jo/Recipick, pull requests merged in 2023-02, with the labels that each got.

#212 [Styled] 스플래시 로고가 안보이는 문제 해결
  src/Assets/Images/logo.svg
  src/Assets/Images/logo_w_name_hq.png
  src/Assets/Images/logo_w_name_hq.svg
  src/Assets/Images/logo_w_name_hq_low.png
  src/Assets/Images/logo_white.svg
  src/Pages/Login/Login.style.jsx
  src/Pages/Splash/Splash.jsx
  src/Pages/Splash/Splash.style.jsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#213 [Fix] 프로필 페이지에서 유저 이미지가 안 보이는 문제 해결
  src/Components/Common/ProfileThumb/ProfileThumb.jsx
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: 🐞 BugFix

#215 [Fix] 다크모드 관련 이슈 해결 / 스타일링 코드 수정
  src/Assets/Icons/icon-arrow-left_white.png
  src/Components/CommentItem/MyCommentInput.style.jsx
  src/Components/CommentItem/UserComment.style.jsx
  src/Components/Common/Alert/Alert.style.jsx
  src/Components/Common/Button/Button.style.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Header/Header.style.jsx
  src/Components/Common/Layout/Layout.jsx
  src/Components/Common/Layout/Layout.style.jsx
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
  src/Components/FollowItem/FollowItem.style.jsx
  src/Components/LoginForm/LoginForm.style.jsx
  src/Components/PostEdit/PostText/PostText.jsx
  src/Components/PostEdit/PostText/PostText.style.jsx
  src/Components/ProductEdit/ProductInput/ProductInput.style.jsx
  src/Cookie/Cookie.js
  src/Pages/Login/Login.style.jsx
  src/Pages/Main/Chat/ChatList/ChatList.jsx
  src/Pages/Main/Chat/ChatRoom/ChatRoom.style.jsx
  src/Pages/Main/Profile/Followers/Followers.jsx
  src/Pages/Main/Profile/Following/Following.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Pages/Signup/Profile/ProfileSet.style.jsx
  src/Pages/Signup/Signup.style.jsx
  src/Style/GlobalTheme.js
Labels: 🎨 HTML&CSS
