Repository Bul-4-Jo/Recipick, pull requests merged in 2023-01, with the labels that each got.

#142 [Feature] 유저 검색창 기능 구현
  src/API/api.js
  src/Components/Common/Header/Header.jsx
  src/Components/Search/SearchBar.jsx
  src/Components/Search/SearchBar.style.jsx
  src/Components/Search/SearchUserItem.jsx
  src/Components/Search/SearchUserItem.style.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Main/Search/Search.style.jsx
  src/Pages/Main/Search/SearchBar.jsx
  src/Pages/Main/Search/SearchUserItem.jsx
Labels: ✨ Feature

#145 [Bug] 해당 유저의 follower/following 리스트를 불러오도록 수정
  src/API/api.js
  src/Pages/Main/Profile/Followers/Followers.jsx
  src/Pages/Main/Profile/Following/Following.jsx
Labels: 🐞 BugFix

#149 [Fix] 판매 중인 상품이 없을 시 해당 영역 제거
  src/Components/Product/Product.jsx
Labels: 🐞 BugFix

#150 [Feat] PostCard 내 UserInfo 클릭 시 올바른 url로 이동할 수 있도록 수정
  src/Components/Common/PostCard/PostCard.jsx
Labels: ✨ Feature

#153 [Refactor] 이미지를 url로 저장하고 요청하도록 수정
  src/API/api.js
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/Product/ProductItem/ProductItem.jsx
  src/Components/ProductEdit/ProductForm/ProductForm.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
Labels: ✨ Feature, 🔨 Refactor

#147 [Feat] 프로필 수정 페이지 헤더 버튼 추가 및 헤더 컴포넌트 리팩토링
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Header/Header.style.jsx
  src/Components/ProfileEdit/ProfileBtn/ProfileBtn.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
Labels: ✨ Feature, 🔨 Refactor

#151 [Feature] 게시물 좋아요 기능 구현
  src/API/api.js
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Reactions/LikeButton.jsx
  src/Components/Reactions/ReactionSection.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
Labels: 📡 API, ✨ Feature

#144 [Feature] 게시물 상세페이지, 댓글 업로드 및 댓글 수 카운팅 기능 구현
  src/API/api.js
  src/Components/Comment/Comment.jsx
  src/Components/Comment/Comment.style.jsx
  src/Components/CommentItem/MyCommentInput.jsx
  src/Components/CommentItem/MyCommentInput.style.jsx
  src/Components/CommentItem/UserComment.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/UserInfo/UserInfo.jsx
  src/Components/Reactions/CommentCounter.jsx
  src/Components/Reactions/ReactionSection.jsx
  src/Components/Reactions/ReactionSection.style.jsx
  src/Pages/Comment/Comment.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Pages/PostDetail.jsx
  src/Routes/Router.jsx
Labels: ✨ Feature

#155 [Fix] 기능 오류 수정 및 개선
  src/API/api.js
  src/Components/Comment/Comment.jsx
  src/Components/Comment/Comment.style.jsx
  src/Components/CommentItem/MyCommentInput.jsx
  src/Components/CommentItem/MyCommentInput.style.jsx
  src/Components/CommentItem/UserComment.jsx
  src/Components/CommentItem/UserComment.style.jsx
  src/Components/Common/BtnUpload/BtnUpload.jsx
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Modal/Modal.jsx
  src/Components/Common/PostAlbum/PostAlbum.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/ProfileThumb/ProfileThumb.jsx
  src/Components/Common/ProfileThumb/ProfileThumb.style.jsx
  src/Components/Common/TabMenu/TabMenu.style.jsx
  src/Components/Common/UserInfo/UserInfo.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/Product/ProductItem/ProductItem.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.jsx
  src/Components/Reactions/CommentCounter.jsx
  src/Components/Reactions/LikeButton.jsx
  src/Components/Reactions/ReactionSection.jsx
  src/Components/Search/SearchBar.jsx
  src/Components/Search/useDebounce.jsx
  src/Hooks/useUploadFile.js
  src/Pages/Main/Chat/ChatList/ChatList.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Pages/Post/PostEdit/PostEdit.jsx
  src/Pages/Signup/Profile/ProfileSet.jsx
Labels: 📡 API, 🐞 BugFix

#156 [Style] 불필요한 주석, 파일 및 콘솔로그 삭제
  README.md
  public/index.html
  src/API/api.js
  src/Components/Comment/Comment.jsx
  src/Components/CommentItem/UserComment.jsx
  src/Components/Common/BtnUpload/BtnUpload.jsx
  src/Components/Common/Button/Button.style.jsx
  src/Components/Common/GetPost/GetPost.style.jsx
  src/Components/Common/Header/Header.jsx
  src/Components/Common/Modal/Modal.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/LoginForm/LoginForm.jsx
  src/Components/ProductEdit/ProductInput/ProductInput.jsx
  src/Components/ProfileEdit/ProfileImg/ProfileImg.jsx
  src/Components/Reactions/CommentCounter.jsx
  src/Components/Reactions/LikeButton.jsx
  src/Components/Search/SearchBar.jsx
  src/Components/Search/SearchBar.style.jsx
  src/Components/Search/useDebounce.jsx
  src/Components/UserSearch.jsx
  src/Hooks/Hook.jsx
  src/Pages/Main/Chat/ChatList/ChatList.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Search/Search.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Signup.jsx
  src/Pages/Splash/Splash.jsx
  src/Routes/Router.jsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#158 [Style] 배경 이미지 변경
  src/Assets/Images/recipick_MainBg.png
  src/Style/GlobalStyle.jsx
Labels: 🎨 HTML&CSS

#160 [Feat] 게시물 상세 페이지에 판매 중인 상품 추가
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
Labels: ✨ Feature

#162 [Fix] 프로필 수정에서 이미지 업로드 오류 수정
  src/Components/ProfileEdit/ProfileBtn/ProfileBtn.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
Labels: 🐞 BugFix

#166 [Fix] comment Input user Image 추가
  src/Components/CommentItem/MyCommentInput.jsx
Labels: 🐞 BugFix

#164 [Feat] report 신고하기 기능 구현
  src/API/api.js
  src/Components/CommentItem/UserComment.jsx
  src/Components/Common/PostCard/PostCard.jsx
Labels: ✨ Feature

#167 Fix: 검색 키워드가 없어도 데이터를 받아오는 오류 수정 및 서버 요청 최적화
  src/Components/Search/SearchBar.jsx
Labels: 🐞 BugFix

#169 [Feat] 공유하기 버튼 클릭시 주소 복사 기능 구현
  src/Components/Common/Alert/Alert.jsx
  src/Components/Common/Alert/Alert.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
Labels: ✨ Feature

#172 [Style] 캐러셀 슬라이드 구현
  src/Assets/Icons/icon_slide_arrow_left.png
  src/Assets/Icons/icon_slide_arrow_right.png
  src/Components/Carousel/Carousel.jsx
  src/Components/Carousel/Carousel.style.jsx
  src/Components/Common/PostCard/PostCard.jsx
Labels: ✨ Feature, 🎨 HTML&CSS

#174 [Feat] 채팅폼 페이지 마크업 및 스타일링
  src/Pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/Pages/Main/Chat/ChatRoom/ChatRoom.style.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Style/GlobalTheme.js
Labels: 🎨 HTML&CSS

#175 [etc] 유저 검색창에서 username과 id를 함께 표시하도록 수정 및 사용하지 않는 파일 삭제
  src/Components/Search/SearchBar.jsx
  src/Components/Search/SearchUserItem.jsx
  src/Components/Search/useDebounce.jsx
Labels: 🎨 HTML&CSS

#176 [fix] 캐러셀 최대 너비 적용
  src/Components/Carousel/Carousel.style.jsx
Labels: 🐞 BugFix

#177 [Style] 채팅이미지 스타일 수정
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
Labels: 🎨 HTML&CSS

#178 [Docs] 리드미 트러블 슈팅 등 작성
  README.md
Labels: 📃 Docs

#183 [Fix] PostCard 컴포넌트에 가로 스크롤이 생기는 이슈 수정
  src/Components/Carousel/Carousel.style.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#184 [Feat] 게시물 업로드시 레시피 템플릿 제공
  README.md
  src/Assets/Images/logo_w_name_hq.png
  src/Assets/Images/logo_w_name_hq.svg
  src/Components/Common/PostCard/PostCard.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
  src/Components/PostEdit/PostBtn/PostBtn.jsx
  src/Components/PostEdit/PostForm/PostForm.jsx
  src/Components/PostEdit/PostText/PostText.jsx
  src/Components/PostEdit/PostText/PostText.style.jsx
  src/Pages/Main/Chat/ChatRoom/ChatRoom.style.jsx
  src/Pages/Splash/Splash.jsx
  src/Pages/Splash/Splash.style.jsx
Labels: ✨ Feature

#188 [Refactor] 무한 스크롤 렌더링 최적화 / API 호출 관련 수정
  src/API/api.js
  src/Components/Common/GetPost/GetPost.jsx
  src/Components/Common/PostCard/PostCard.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: 📡 API, 🔨 Refactor

#186 [fix] 이미지가 없는 게시물인 경우 GetImg 컴포넌트를 적용하지 않도록 수정
  src/Components/Common/PostCard/PostCard.jsx
Labels: 🐞 BugFix

#196 [Fix] 게시글 상세 페이지에 삭제 기능 추가
  src/Pages/Post/PostDetail/PostDetail.jsx
Labels: 🐞 BugFix, ✨ Feature

#197 [Refactor] 검색 기능 최적화
  src/API/api.js
  src/Components/Search/SearchBar.jsx
  src/Hooks/useDebounce.js
Labels: ✨ Feature, 🔨 Refactor

#200 [Style] 프로필 페이지 유저 썸네일 중앙정렬
  public/favicon.ico
  public/index.html
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#199 [Refactor] 일부 페이지에서 탭 메뉴 삭제
  src/Components/Common/Layout/Layout.style.jsx
  src/Components/Common/TabMenu/TabMenu.jsx
  src/Components/PostEdit/PostForm/PostForm.style.jsx
  src/Components/PostEdit/PostImg/PostImg.style.jsx
Labels: 🔨 Refactor

#210 [Fix] 375px 에서 모달이 잘려보이는 문제 해결
  src/Components/Common/Modal/Modal.style.jsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#207 [Refactor] 경고 메세지 표시 되는 경우 밀림 현상 제거
  src/Components/LoginForm/LoginForm.jsx
  src/Components/LoginForm/LoginForm.style.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.jsx
  src/Pages/Main/Profile/ProfileEdit/ProfileEdit.style.jsx
  src/Pages/Signup/Profile/ProfileSet.jsx
  src/Pages/Signup/Profile/ProfileSet.style.jsx
  src/Pages/Signup/Signup.jsx
  src/Pages/Signup/Signup.style.jsx
Labels: 🎨 HTML&CSS

#204 [Fix] 프로필 이미지가 제대로 로드되지 않는 오류 수정
  src/Components/Common/ProfileThumb/ProfileThumb.jsx
  src/Components/Search/SearchUserItem.jsx
Labels: 🐞 BugFix

#191 [Feat] 다크모드 기능 구현
  package-lock.json
  package.json
  src/Assets/Icons/icon_home_fill.png
  src/Components/CommentItem/MyCommentInput.style.jsx
  src/Components/Common/BtnDarkMode/BtnDarkMode.jsx
  src/Components/Common/BtnDarkMode/BtnDarkMode.style.jsx
  src/Components/Common/GetPost/GetPost.style.jsx
  src/Components/Common/Header/Header.style.jsx
  src/Components/Common/Layout/Layout.jsx
  src/Components/Common/Layout/Layout.style.jsx
  src/Components/Common/PostCard/PostCard.style.jsx
  src/Components/Common/UserInfo/UserInfo.style.jsx
  src/Components/PostEdit/PostTag/PostTag.style.jsx
  src/Components/PostEdit/PostText/PostText.style.jsx
  src/Components/Reactions/ReactionSection.style.jsx
  src/Components/Search/SearchBar.style.jsx
  src/Hooks/useTheme.js
  src/Pages/Login/Login.style.jsx
  src/Pages/Main/Chat/ChatList/ChatItem/ChatItem.style.jsx
  src/Pages/Main/HomeFeed/HomeFeed.jsx
  src/Pages/Main/Profile/UserProfile/UserProfile.style.jsx
  src/Style/GlobalTheme.js
  src/Style/ThemeProvider.jsx
  src/index.js
Labels: ✨ Feature, 🎨 HTML&CSS

#209 [Refactor] token 저장 위치를 localStorage에서 cookie로 변경
  README.md
  package-lock.json
  package.json
  src/API/api.js
  src/Components/Common/Header/Header.jsx
  src/Components/LoginForm/LoginForm.jsx
  src/Cookie/Cookie.js
  src/Pages/Splash/Splash.jsx
  src/Routes/AuthRoute.jsx
  src/Routes/NonAuthRoute.jsx
Labels: 🔨 Refactor
